### ISSUE TITLE
How to open the .bc file which generated by GenerationTrainData.m ?

### ISSUE THREAD

**Issue by li-yao** [alfredtorres/3DFacePointCloudNet#3]
How to open the .bc file which generated by GenerationTrainData.m ?

**Comment by alfredtorres** [comment]
https://github.com/alfredtorres/3DFacePointCloudNet/blob/9a857ed9619ddaebe99bfb6bd75462e4f3055e75/pointnet2/data/GPMM_Normal_Curvature_dataset.py#L22
this function can read .bcnc format, if you want to read .bc filen you can just modify the cols to 3.
